program: rivian
name: trips
read_stream:
  format: cloudFiles
  options:
    pathGlobFilter: "*.csv"
    recursiveFileLookup: true
    cloudFiles.format: csv
    cloudFiles.maxFilesPerTrigger: "5"
    cloudFiles.queueUrl: https://sqs.us-east-1.amazonaws.com/785562577411/IotRivianTrips
    cloudFiles.region: us-east-1
    cloudFiles.useNotifications: true
    cloudFiles.includeExistingFiles: false
    cloudFiles.validateOptions: true
  source_s3_location: s3://pcds-internal-iot-rivian-telematics-785562577411/rivian-sourcefiles/daily/
write_stream:
  trigger:
    availableNow: True
  options:
    checkpointLocation: s3://pc-iot-raw-785562577411/rivian/checkpoints/trips
micro_batch:
  mode: append
  save_as:
    table: trips
    schema: dhf_iot_rivian_raw_prod